// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkL4nOmdhfeUvAZDD-3ulrXRwHQf48pc',
    appId: '1:431719662285:web:4b1cbf9e203bd00b4f1f84',
    messagingSenderId: '431719662285',
    projectId: 'paintmanager-21dad',
    authDomain: 'paintmanager-21dad.firebaseapp.com',
    storageBucket: 'paintmanager-21dad.firebasestorage.app',
    measurementId: 'G-7RVDK4GYSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDQNt_KvjrkD6xgU64f0X-q8GfsZ_AEL4',
    appId: '1:431719662285:android:2df962f1dab95fb14f1f84',
    messagingSenderId: '431719662285',
    projectId: 'paintmanager-21dad',
    storageBucket: 'paintmanager-21dad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFJTi2Ie6F--ORX8ZpzaQFFj-lXGg52Cg',
    appId: '1:431719662285:ios:2b65becce582b1e34f1f84',
    messagingSenderId: '431719662285',
    projectId: 'paintmanager-21dad',
    storageBucket: 'paintmanager-21dad.firebasestorage.app',
    iosClientId: '431719662285-1bb2ufcgkbkut8em8153jvebst5p8n6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.paintmanagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFJTi2Ie6F--ORX8ZpzaQFFj-lXGg52Cg',
    appId: '1:431719662285:ios:2b65becce582b1e34f1f84',
    messagingSenderId: '431719662285',
    projectId: 'paintmanager-21dad',
    storageBucket: 'paintmanager-21dad.firebasestorage.app',
    iosClientId: '431719662285-1bb2ufcgkbkut8em8153jvebst5p8n6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.paintmanagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApkL4nOmdhfeUvAZDD-3ulrXRwHQf48pc',
    appId: '1:431719662285:web:2b9c9472df24f66c4f1f84',
    messagingSenderId: '431719662285',
    projectId: 'paintmanager-21dad',
    authDomain: 'paintmanager-21dad.firebaseapp.com',
    storageBucket: 'paintmanager-21dad.firebasestorage.app',
    measurementId: 'G-0D9Z8CG0BS',
  );
}
